### ISSUE TITLE
How could I modify your spam counter to make it not case-sensitive? 

### ISSUE THREAD

**Issue by Calver** [Blasman/mIRC-Twitch-Scripts#2]
Title pretty much says it all, no idea where to start.
Thanks in advance

**Comment by Blasman** [comment]
I was under the assumption that it is not case sensitive. I am unsure how to make it not case sensitive if it is indeed case sensitive, sorry.

**Comment by Calver** [comment]
Oh. Maybe it isn't! I'll check now, I assumed it was!

**Comment by Calver** [comment]
Its not case sensitive, silly me! I assumed wrongly, sorry for wasting your time.
