### ISSUE TITLE
Sorry I wanted to ask you something but I'm not sure how to...

### ISSUE THREAD

**Issue by Calver** [Blasman/mIRC-Twitch-Scripts#3]
Do you have any mIRC scripts for notifying the chat of new follows and subscribers?

**Comment by Blasman** [comment]
I haven't bothered with a subscriber script as I'm not a partnered streamer. I have made a new follow script, but it is not on the GitHub as it is rather redundant as AnkhBot also welcomes new followers.

**Comment by Calver** [comment]
Where in AnkhBot is this function? Do you mind if I use your code in a bot I'm writing (just for myself)?

**Comment by Blasman** [comment]
It's in the "Settings" tab in AnkhBot. Feel free to use whatever code you want. :)

**Comment by Calver** [comment]
I'm rather confused, is it in ankhbot.mrc?

**Comment by Blasman** [comment]
It's AnkhBot, the program.
