### ISSUE TITLE
Slots won't turn on?

### ISSUE THREAD

**Issue by Moochie** [Blasman/mIRC-Twitch-Scripts#5]
Hi, I am trying to setup slots on my channel.  The !slot command works giving me the correct message in response.  When I place a bet I am told that slot game is currently disabled, so I ran the !slot on command but nothing seems to happen. Thoughts?
Thanks.

**Comment by Blasman** [comment]
Make sure that you are running all the required scripts listed in the instructions.

**Comment by Moochie** [comment]
I believe the issue was is that I didn't reconnect to the twitch chat after loading all my scripts, they seem to be working now.

**Comment by AycheKay** [comment]
Hello, I am having this issue as well. I've run all the necessary scripts, reconnected to twitch chat, and have even restarted the mIRC client.
