### ISSUE TITLE
Having mTwitch.DisplayName.mrc issues

### ISSUE THREAD

**Issue by SharpiePlays** [Blasman/mIRC-Twitch-Scripts#6]
I have been using these scripts for months with no issues. After the twitch client-ID api change I can not get my irc client to play nice. I narrowed it down to this script mTwitch.DisplayName.mrc
When this is loaded and I connect to irc.twitch.tv the status window shows I connect fine. The channel I am going into does not pop open at all, everything stays in the status window, user names ect. I see no chat. 

Now when I unload mTwitch.DisplayName.mrc and reconnect I am able to get back into the channel fine like before and see chat / user list on the right.

Any idea what I might have to do to get around or fix this?

**Comment by Blasman** [comment]
Please update your mTwitch.DisplayName.mrc file. The author has updated it recently so that it will function properly.
